server:
  port: 8705

#应用名称
spring:
  application:
    name: server-zuul
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/xqiangme/spring-could-example/
          searchPaths: config-file
          username:
          password:

